### ISSUE TITLE
Deploy Fails

### ISSUE THREAD

**Issue by kamikazechaser** [jonathan-kosgei/sc-issues#1]
**Issue 1**

Type: Node.js
Addons: None
Repo: [kamikazechaser/ServerBot](https://github.com/kamikazechaser/ServerBot)
Entry: app.js

Here Is The Log:

```bash
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 938 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)
error: fatal: RPC failed; HTTP 504 curl 22 The requested URL returned error: 504 Gateway Time-out
The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date

**Comment by kamikazechaser** [comment]
**Issue 2**

Type: Node.js
Addons: None
Repo: [kamikazechaser/pwr-status](https://github.com/kamikazechaser/pwr-status)
Entry: app.js

I changed the entry point to app.js and set port at 8080

It Deployed successfully but didnt run as expected. Home page shows a error 502

**Comment by jonathan-kosgei** [comment]
Hey Mohammed,
Thank you for taking the time to file an issue.
I'll take a better look at this early tomorrow morning, it'd help if we're
able to IM to make communication easier, so I'm going to message you on
hangouts hope that's okay.

Will get back to you tomorrow.

Regards,
Jonathan

On Nov 5, 2016 8:58 PM, "Mohammed Sohail" notifications@github.com wrote:

Here Are The Logs:

Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 938 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)
error: fatal: RPC failed; HTTP 504 curl 22 The requested URL returned
error: 504 Gateway Time-out
The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date```

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/jonathan-kosgei/sc-issues/issues/1, or mute the thread

**Comment by kamikazechaser** [comment]
Ok, I will be available

**Comment by jonathan-kosgei** [comment]
@kamikazechaser Hey Mohammed, sorry for the delay, school kinda took over with exams and everything :)
The first issue you got, and the reason the push worked the second time was because the git container takes a few seconds to start and setup the endpoint so as much as your app has been created there's a delay before you can push to the git endpoint.
The second issue was that all apps are exposed on port 80 :) I realise not getting to set the ports for esp node apps is not intuitive and I'll have to figure out a way around it or document it better. Probably document it better.

**Comment by kamikazechaser** [comment]
Alright, I'll wait for the documentation fro node.js.

**Comment by jonathan-kosgei** [comment]
Hi @kamikazechaser filed this bug with npm https://github.com/npm/npm/issues/15422 .
It's a dependency issue with the module `diskusage`
Also, all node apps need specify their entrypoint in an `app.js` file, and expose the app at 8080 so no issue there. I updated this for you server side and debugged as far as I could get.

**Comment by kamikazechaser** [comment]
Ok, so which ports are exposed upn deploying node apps, 8080 or 80 or is it any?

**Comment by jonathan-kosgei** [comment]
Port 8080, however there's an nginx instance infront of every node app that proxies it at port 80, meaning once you have a node app running it'll automatically be made available at port 80 by nginx.
Here's a simplistic app I set up earlier for testing: http://test-node.saharacluster.com/
Based on the code at: https://github.com/jonathan-kosgei/sc-examples/tree/master/node

**Comment by jonathan-kosgei** [comment]
Set your app to run on port 8080, the platform takes care of the rest.

**Comment by kamikazechaser** [comment]
My app needs to specifically listen to POST calls to only 80 or 443

**Comment by jonathan-kosgei** [comment]
In the repo, where have you specified the ports to listen to? Makes sense, currently any calls to port 80 will be forwarded to your app at port 8080, does this make sense? I haven't added support for ssl, still haven't launched officially but will likely get those before a beta launch. But I can add it if you can live with self-signed certs? For now?

**Comment by kamikazechaser** [comment]
Alright, I needed that clarification cause it wasn't documented anywhere. Yeah SSL is necessary, I'm ok with self signed certs.

**Comment by jonathan-kosgei** [comment]
Okay I'll add this to what I'm working on, I'm also working on:
 - A CLI tool similar to the heroku toolbelt
 - TTY; ability to attach a shell to your app
 - And exposing app logs, so that you'd have been able to debug this situation without me :)
Thank you for trying out the platform! :) Stay tuned! Hope you don't mind if I email you with updates, on these, as well as updates from the issue on npm's repo.

**Comment by kamikazechaser** [comment]
Sure keep me updated via email!
